Prevent Exception from raising an Exception
RegistrationError gets raise'd, so it should be an Exception and behave
like one.

This fixes

>>> raise RegistrationError('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: RegistrationError() takes no arguments